package com.example.lookup.domain.home

import kotlinx.coroutines.Deferred

/**
 * Represents a single message in a conversation.
 *
 * @property role The role of the participant who sent the message.
 * @property content The content of the message.
 */
data class ConversationMessage(
    val role: Role,
    val content: String
) {
    /**
     * An enum value that indicates the role of the participant who sent the message.
     */
    enum class Role {
        /**
         * Represents an AI assistant.
         */
        Assistant,

        /**
         * Represents the user..
         */
        User
    }
}

/**
 * Represents a single message in a conversation.
 */
sealed interface ConversationMessageV2 {
    /**
     * Represents a message generated by an AI assistant.
     */
    data class AssistantMessage(val content: Content) : ConversationMessageV2 {
        /**
         * A sealed class hierarchy that consists of all the different content types
         * associated with an instance of [AssistantMessage].
         */
        sealed interface Content {
            /**
             * Represents a message that will be asynchronously generated by the AI assistant.
             */
            data class DeferredContent(val deferredContent: Deferred<String>) : Content

            /**
             * Represents a message that was already generated by the AI assistant.
             */
            data class Immediate(val immediateContent: String) : Content
        }
    }

    /**
     * Represents a message sent by the user.
     */
    data class UserMessage(val content: String) : ConversationMessageV2

}